cursor #e1e1ef
cursor_text_color #c5c6d3

foreground            #e1e1ef
background            #10131c
selection_foreground  #2e2d4d
selection_background  #c6c2ea
url_color             #b5c4ff

color0   #10131c
color1   #ff7297
color2   #7fff94
color3   #fff972
color4   #9daef2
color5   #374376
color6   #b5c4ff
color7   #eff2ff
color8   #404249
color9   #ff9fb8
color10  #a5ffb4
color11  #fffba5
color12  #c0ccff
color13  #cbd5ff
color14  #dde4ff
color15  #f8f9ff
